// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycronkpfnxmydrkgamel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inljcm9ua3BmbnhteWRya2dhbWVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMDE1MzcsImV4cCI6MjA3Mjg3NzUzN30.fyUnLNIs2AfJ4W81E39lScEvvRPb93eFGXFO6_7aK_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});